### ISSUE TITLE
Make Pair

### ISSUE THREAD

**Issue by Ankit152** [Ankit152/CPP-STL#1]
Given two elements X and Y. The task is to return the pair formed from a function `makePair` with given elements. Use `make_pair` from Pair.

Constraints:
1 <= T <= 100
1 <= X, Y <= 1000

Sample Input:
2
4 5
1 0

Sample Output:
(4,5)
(1,0)

**Comment by saptarshiweb** [comment]
Hi,
I have a good understanding of C++ STL , I would write clean and documented code. I am interested to work on this issue. Kindly , assign this issue to me.
@Ankit152
Regards,
Saptarshi Mandal
