### ISSUE TITLE
Vector Erase and Clear 

### ISSUE THREAD

**Issue by Ankit152** [Ankit152/CPP-STL#10]
Given a Vector V of size N containing integers. Complete below functions on given vector depending on type of erasable query

1. clearAll(): This function removes all elements from vector.
2. eraseAt(): This function removes element from specified position present in the vector.
3. eraseInRange(): This function removes element from vector in the given range start & end.

**Comment by ap1809** [comment]
Hi,
I am interested to solve this issue. So I would request you to assign this issue to me.
@Ankit152
Regards,
Angsuman Patra

**Comment by anuragc2001** [comment]
This will be my first ever open-source contribution if you kindly assign me this issue @Ankit152.
Thanking you,
Anurag Chakraborty

**Comment by Ankit152** [comment]
@anuragc2001 you can checkout for other issues. You can also create issues if you want. You can also contribute by properly updating the readme.

**Comment by anuragc2001** [comment]
@Ankit152 I'm willing to work on this issue. Kindly please assign me the issue.
