### ISSUE TITLE
Find the Frequency

### ISSUE THREAD

**Issue by Ankit152** [Ankit152/CPP-STL#11]
Given a vector of N positive integers and an integer X. The task is to find the frequency of X in `vector`.

Input:
N = 5
vector = {1, 1, 1, 1, 1}
X = 1

Output: 
5

**Comment by debanjan-2002** [comment]
Hi,
I have a good grip in C++ and have sound knowledge of different C++ STL containers and their methods. I would write clean and documented code. Hence I would request you to assign this issue to me.
@Ankit152 
Regards,
Debanjan Poddar

**Comment by Ankit152** [comment]
Hi @debanjan-2002 
I have assigned you this issue you can start to work on it. Also try to share the repo with all your fellow mates who have good grip in C++ so that they can also contribute in this project.
