### ISSUE TITLE
Pairing Elements

### ISSUE THREAD

**Issue by Ankit152** [Ankit152/CPP-STL#2]
Given an array of elements of size N containing positive integers. The task is to make pair of elements given in array such that 1st element will be paired with last element, 2nd element with 2nd last, 3rd element with 3rd last and so on. If the array is of odd size then make middle element as a pair with itself.

Input Format: The input line contains T, denoting the number of testcases. For each testcase there will be two lines. The first line contains size of array N, second line contains elements of the array separated by space. Use `pairs`.

Output Format: For each testcase, in a new line, you need to print the pairs formed as such (arr[0],arr[N-1]) (arr[1],arr[N-2]), and so on in new line.

Constraints:
1 <= T <= 100
1 <= N <= 1000
1 <= arr[i] <= 1000

Sample Input:
2
5
1 2 3 4 5
4
4 2 3 1

Sample Output:
(1,5) (2,4) (3,3)
(4,1) (2,3)

**Comment by saptarshiweb** [comment]
Hi,
I have a good understanding of C++ STL , I would write clean and documented code. I am interested to work on this issue. Kindly , assign this issue to me.
@Ankit152 
Regards,
Saptarshi Mandal
