### ISSUE TITLE
Elements Less Than K

### ISSUE THREAD

**Issue by Ankit152** [Ankit152/CPP-STL#20]
A vector a of size n and an element k are given to you. You need to return the list(vector) of elements less than k. The order of elements should be the same as that in the original array.

Input:
n = 5
vector -> 5 3 6 1 3
k = 4
Output: 
3 1 3

**Comment by debanjan-2002** [comment]
Hi,
Please assign this issue to me. I will do it in O(n) time complexity.
@Ankit152 

Regards,
Debanjan Poddar
