### ISSUE TITLE
Sort Vector of Pairs

### ISSUE THREAD

**Issue by Ankit152** [Ankit152/CPP-STL#21]
Given a vector of pairs of size n where first element of pair is the age and the second element is the height, you need to sort the vector of pairs in descending order by the second item of the pair. And if the second items are equal, then sort it by first element.

Example:
Input:
2
2
1 4 2 4
2
1 6 2 10

Output:
(2,4) (1,4)
(2,10) (1,6)

**Comment by saptarshiweb** [comment]
Hi,
I have a good understanding of C++ STL. I am interested to solve this problem. Kindly, assign this issue to me.
@Ankit152
Regards,
Saptarshi Mandal

**Comment by anuragc2001** [comment]
I'm interested to solve this problem. This will be my first ever open-source contribution if you kindly assign me this issue @Ankit152.
Thanking you,
Anurag Chakraborty
