### ISSUE TITLE
Forward List Insert

### ISSUE THREAD

**Issue by Ankit152** [Ankit152/CPP-STL#22]
You are given an array of size n. You need to insert the elements of this array in to a forward list.

Input:
1
5
1 2 3 4 5
Output:
5 4 3 2 1

**Comment by saptarshiweb** [comment]
Hi,
I have a good understanding of C++ STL. I am interested to solve this problem. Kindly, assign this issue to me.
@Ankit152
Regards,
Saptarshi Mandal
