### ISSUE TITLE
Dequeue Traversal

### ISSUE THREAD

**Issue by Ankit152** [Ankit152/CPP-STL#24]
Given a Deque Deq containing N elements, the task is to traverse the Deq and print the elements of it. 

Input: 
5
1 2 3 4 5

Output: 
1 2 3 4 5

**Comment by debanjan-2002** [comment]
Hi,
Please assign this issue to me. I will do this with deque class from C++ STL.
@Ankit152 

Regards,
Debanjan Poddar
