### ISSUE TITLE
Deque deletion

### ISSUE THREAD

**Issue by Ankit152** [Ankit152/CPP-STL#26]
Given a Deque dqe of size N containing non-negative integers.

Complete below functions depending type of query as mentioned and provided to you (indexing starts from 0):
1. eraseAt(X): this function should remove the element from specified position X in deque.
2. eraseInRange(start, end): this function should remove the elements in range start (inclusive), end (exclusive) specified in the argument of the function.
Note: If start is equal to end then simply return.
3. eraseAll(): remove all the elements from the deque.

Input:
5
1 2 4 5 6
1 2

Output: 
1 2 5 6

**Comment by RaySourish** [comment]
Hi,
I am interested to solve this issue. So I would request you to assign this issue to me.
@Ankit152
Regards,
Sourish Ray
