### ISSUE TITLE
Reverse Array Using Stack

### ISSUE THREAD

**Issue by Ankit152** [Ankit152/CPP-STL#28]
You are given an array arr[] of size N, the task is to reverse the array elements by using a stack.

Input: N = 5, arr[] = {1, 2, 3, 4, 5}
Output: 5 4 3 2 1

**Comment by Aquasin** [comment]
Hi Ankit. I am Shashank and I am a beginner in open source contribution. I just wanted to ask if I could help in this issue?

**Comment by maityamit** [comment]
Hi , Ankit I am Amit , I want to do this .. can I do it now ?

**Comment by Ankit152** [comment]
@maityamit this issue is already assigned. You may look form other issues.

**Comment by maityamit** [comment]
@Ankit152  Thanks

**Comment by sahilrik** [comment]
hi, i am Sahil Barua i want to work on this issue can you kindly assign this to me
