### ISSUE TITLE
Corresponding `pair`

### ISSUE THREAD

**Issue by Ankit152** [Ankit152/CPP-STL#3]
Given two arrays arr1[] and arr2[] of size N. The task is to make pairs containing values corresponding from arr1 and arr2 i.e. (arr1[0], arr2[0]), (arr1[1],arr2[1]) and so on.

Input Format: The input line contains T, number of testcases. Each testcase contains three lines. The first line contains N size of both arrays. The second and third line contains elements of two arrays separated by space.

Output Format: For each testcase, in a new line, you have to return an array of pairs formed with given arrays.

Constraints:
1 <= T <= 100
1 <= N <= 100
1 <= arr1[i], arr2[j] <= 100

Sample Input:
2
5
1 2 3 4 5
6 7 8 9 10
2
1 2
3 4

Sample Output:
(1,6) (2,7) (3,8) (4,9) (5,10)
(1,3) (2,4)

**Comment by saptarshiweb** [comment]
Hi,
I have a good understanding of C++ STL , I would write clean and documented code. I am interested to work on this issue. Kindly , assign this issue to me.
@Ankit152
Regards,
Saptarshi Mandal
