### ISSUE TITLE
Deletion from deque

### ISSUE THREAD

**Issue by shubhamsharma6701** [Ankit152/CPP-STL#45]
Given a deque of size N, we need to delete elements from its front end one-by-one depending upon the user's choice. 

Input: 

2 3 5 6 1 

Output:

3 5 6 1 
Do you wish to delete one more element(y/n)?y

5 6 1 
Do you wish to delete one more element(y/n)?y

6 1
Do you wish to delete one more element(y/n)?n

Note - The program will also notify when the deque will become empty.

**Comment by Ankit152** [comment]
are you working on this issue?

**Comment by shubhamsharma6701** [comment]
The code for this issue has already been added in the deque folder.
