### ISSUE TITLE
`Vector` insertion

### ISSUE THREAD

**Issue by Ankit152** [Ankit152/CPP-STL#5]
Given an array arr[] of size N containing integers. The task is to insert elements of given array to vector and return that vector and print it.

Input:
N = 4
arr[] = 1 2 3 4

Output: 
1 2 3 4

**Comment by debanjan-2002** [comment]
Hi,
I have a good grip in C++ and have sound knowledge of different C++ STL containers and their methods. I would write clean and documented code. Hence I would request you to assign this issue to me.
@Ankit152 
Regards,
Debanjan Poddar
