### ISSUE TITLE
Front to Back

### ISSUE THREAD

**Issue by Ankit152** [Ankit152/CPP-STL#6]
Iterators are used to iterate over vectors, maps, sets etc. Here you have to iterate over a `vector` from begin to end.
You are given a vector V of size n. You need to print its elements.

Input:
N = 5
vector -> 1 2 3 4 5
Output: 
1 2 3 4 5

**Comment by saptarshiweb** [comment]
Hi,
I have a good understanding of C++ STL , I would write clean and documented code. I am interested to work on this issue. Kindly , assign this issue to me.
@Ankit152 
Regards,
Saptarshi Mandal
