### ISSUE TITLE
Vector Sum

### ISSUE THREAD

**Issue by Ankit152** [Ankit152/CPP-STL#8]
Given a `vector`, find the sum of the elements of this vector.

Input:
10 20 30

Output: 
60

**Comment by debanjan-2002** [comment]
Hi,
I have a good grip in C++ and have sound knowledge of different C++ STL containers and their methods. I would write clean and documented code. Hence I would request you to assign this issue to me.
@Ankit152 
Regards,
Debanjan Poddar

**Comment by ap1809** [comment]
Hi,
I am interested to solve this issue. So I would request you to assign  this issue to me.
@Ankit152 
 Regards,
Angsuman Patra
