### ISSUE TITLE
Sort and Reverse Vector

### ISSUE THREAD

**Issue by Ankit152** [Ankit152/CPP-STL#9]
You are given a `vector` V of size n. You need to sort it and reverse it.

Input:
n = 5
V = 1 2 3 4 5

Output: 
1 2 3 4 5
5 4 3 2 1

**Comment by debanjan-2002** [comment]
Hi,
I have a good grip in C++ and have sound knowledge of different C++ STL containers and their methods. I would write clean and documented code. Hence I would request you to assign this issue to me.
@Ankit152 
Regards,
Debanjan Poddar

**Comment by ap1809** [comment]
Hi,
I am interested to solve this issue. So I would request you to assign this issue to me.
@Ankit152
Regards,
Angsuman Patra

**Comment by Ankit152** [comment]
@ap1809 You can checkout for other issues otherwise if you want to work on any and it is not listed you can also create it.
